"""Abstract base class for chain generation strategies."""

from abc import ABC, abstractmethod

import networkx

from graphqler.chains.chain import Chain
from graphqler.graph.node import Node


class BaseChainStrategy(ABC):
    """Abstract base class for dependency-chain generation strategies.

    Subclasses implement :meth:`generate` to produce a list of :class:`Chain` objects
    from the dependency graph and a set of starter nodes, and declare a :attr:`file_name`
    that determines where the chains are persisted under the ``compiled/chains/`` folder.
    """

    #: Filename (relative to ``compiled/chains/``) for persisting this strategy's output.
    file_name: str

    @abstractmethod
    def generate(self,
                 graph: networkx.DiGraph,
                 starter_nodes: list[Node],
                 source_chains: list[Chain] | None = None,
                 filter_mutation_type: list[str] | None = None) -> list[Chain]:
        """Generate chains from the dependency graph.

        Args:
            graph (networkx.DiGraph): The compiled dependency graph.
            starter_nodes (list[Node]): Root nodes (nodes with no, or minimal, in-degree).
            source_chains (list[Chain] | None): Chains generated by a previous strategy.
            filter_mutation_type (list[str] | None): Mutation types whose nodes should be
                excluded from generated chains (and whose subtrees are not traversed).
                Pass an empty list or ``None`` to include all nodes. Defaults to ``None``.

        Returns:
            list[Chain]: The generated chains.
        """
        ...

    def is_enabled(self) -> bool:
        """Return True if this strategy is enabled and should be run."""
        return True
