name: Run checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements.txt
      - name: Record coverage
        run: |
          python -m coverage html
      - name: Upload coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 4172ebd5ed2de5625710515b639d0fa3cfd4820cb3f35c5c54d018d8404e702c
