name: Run code-climate checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install
          sudo apt install -y $(grep -o ^[^#][[:alnum:]-]* "packages.list")
          python3 -m pip install --upgrade pip

      # - name: Upload coverage
      #   uses: paambaati/codeclimate-action@v3.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: 4172ebd5ed2de5625710515b639d0fa3cfd4820cb3f35c5c54d018d8404e702c
      #   with:
      #     coverageCommand: pytest --exitfirst --verbose --failed-first --cov=. --cov-report xml
