name: Integration tests

on: [push, pull_request]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up poetry
      run: |
        pip install poetry
        poetry install

    - name: Install Python dependencies
      run: poetry install

    - name: Run integration test for food delivery API
      run: |
        poetry run pytest tests/integration/test_food_delivery_api.py --exitfirst --verbose --failed-first --cov=. --cov-report html
    
    - name: Run integration test for user wallet API
      run: |
        poetry run pytest tests/integration/test_user_wallet_api.py --exitfirst --verbose --failed-first --cov=. --cov-report html
