name: Integration tests

on: [push, pull_request]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Node.js dependencies
      working-directory: tests/test-apis/food-delivery-api
      run: npm install

    - name: Initialize database
      working-directory: tests/test-apis/food-delivery-api
      run: node dbinitializer.js

    - name: Start Node.js server
      working-directory: tests/test-apis/food-delivery-api
      run: node server.js &
      env:
        PORT: 4000  # Set the port if needed

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up poetry
      run: |
        pip install poetry
        poetry install

    - name: Install Python dependencies
      run: poetry install

    - name: Run integration test
      run: |
        poetry run pytest tests/integration/ --exitfirst --verbose --failed-first --cov=. --cov-report html
